### ISSUE TITLE
It is not possible to globally specifiy the TinyMCE version

### ISSUE THREAD

**Issue by roberthunt** [CakeDC/TinyMCE#31]
The path to TinyMCE has a default value in TinyMCEHelper.php which is set to '/TinyMCE/js/tiny_mce/tiny_mce.js'. It is not possibly to globally override this value and specify an alternative version of TinyMCE without having to pass additional settings to the helper during construction in the controller.

It would be nice to have a global setting that can be used to specify which version is used.

**Comment by omnuvito** [comment]
Hi @roberthunt, this feature has been developed, you can check it in the release [#1.4.0](https://github.com/CakeDC/TinyMCE/releases/tag/1.4.0).
