### ISSUE TITLE
Documentation issues: missing JQuery requirement, bad Plugin name

### ISSUE THREAD

**Issue by ctgraham** [CakeDC/TinyMCE#33]
The version of TinyMCE in HEAD of master (https://github.com/CakeDC/TinyMCE/tree/553db5b1248ec3c8df1636303e4b28b13997a8de) uses the jQuery version of TinyMCE, but the documentation does not state that requirement.  Also, the Installation documentation incorrectly references the Migrations plugin.

**Comment by steinkel** [comment]
Fixed in our latest release https://github.com/CakeDC/TinyMCE/releases/tag/1.3.0
