### ISSUE TITLE
TinyMCE plugin not putting tinymce scripts

### ISSUE THREAD

**Issue by sagarguhe** [CakeDC/TinyMCE#35]
I am using the plugin as it is mentioned in the documentation. Somewhere it is working fine with no issues. But in some part of my application, basically, where the methods are prefixed with admin, it is not working.

I did the usual thing like:
Controller:
$this->helpers = array('TinyMCE.TinyMCE');

View:
$this->TinyMCE->editor('simple');

But I don't know why it is not placing .js file(s) required by the tinymce, where as somewhere it is working.

also I tried putting the required script this way:-
$this->Html->script('/TinyMCE/js/tiny_mce/tiny_mce.js', array(
    'inline' => false
));

OR 

echo $this->Html->script('/TinyMCE/js/tiny_mce/tiny_mce.js', array(
    'inline' => false
));

What should be the problem?

**Comment by omnuvito** [comment]
Hi @sagarguhe, you can find a docs update in the develop branch, you must use public $helper instead, you need add $this->TinyMCE->editor('simple'); at the view that you need the TinyMCE and the 'simple' configuration must be in the bootstrap file, also, you need load the jquery file for the plugin to works. All of these things are in the documentation.
