### ISSUE TITLE
Error when saving

### ISSUE THREAD

**Issue by xtakku** [CakeDC/TinyMCE#36]
In CakePHP 2.6.3, I get the following error when trying to save my post in a form that uses the TinyMCE helper:

"Error: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'transform' at line 1"

I'm using XAMPP v1.8.3 as testing enviroment so PHP version should be 5.5.15.

Edit: Forgot to mention, the TinyMCE editor didn't load at all out of the box; I replaced it with TinyMCE 3.5.11 downloaded from tinymce.com to fix this. I don't know if this is related to my issue.

**Comment by omnuvito** [comment]
Hi @xtakku, can you send the code with the TinyMCE helper settings, forms? This would help us to see where the problem is. Thanks.

**Comment by davidcm86** [comment]
Does not work in cakephp 3.2, I cant do it working. Missing Helper all the time and I followed doc. Thanks.
