### ISSUE TITLE
TinyMCE not selecting textarea (nothing happens)

### ISSUE THREAD

**Issue by clevertechie** [CakeDC/TinyMCE#47]
CakePHP seems to be loading the plugin because I'm not getting any errors when loading from bootstrap, including the helper in the control and then using it in the view, but nothing happens to my `<textarea></textarea>` tags which I placed before and after the script in the view. I have also loaded jQuery. Any ideas on what might be wrong?

Controller:
`public $helpers = ['TinyMCE.TinyMCE'];`

View:
<textarea></textarea>
`$this->TinyMCE->editor(array('theme' => 'advanced'));`
<textarea></textarea>

HTML (view source, when the page is loaded):

```
<textarea>
</textarea>

<script>
//<![CDATA[
tinymce.init({
script : "/TinyMCE/js/tiny_mce/tiny_mce.js",
load_script : "1",
theme : "advanced"
});
//]]>
</script>

<textarea>
</textarea>

```

Bootstrap:

```
Plugin::load('TinyMCE', ['autoload' => true]);

Configure::write('TinyMCE.configs', array(
'advanced' => array(
    'mode' => 'textareas',
    'theme' => 'advanced',
    'plugins' => 'emotions,spellchecker,advhr,insertdatetime,preview',
    'theme_advanced_buttons1' => 'newdocument,|,bold,italic,underline,|,justifyleft,justifycenter,justifyright,fontselect,fontsizeselect,formatselect',
    'theme_advanced_buttons2' => 'cut,copy,paste,|,bullist,numlist,|,outdent,indent,|,undo,redo,|,link,unlink,anchor,image,|,code,preview,|,forecolor,backcolor',
    'theme_advanced_buttons3' => 'insertdate,inserttime,|,spellchecker,advhr,,removeformat,|,sub,sup,|,charmap,emotions',
    'width' => '700',
    'theme_advanced_toolbar_location' => 'top',
    'theme_advanced_toolbar_align' => 'left',
    'theme_advanced_statusbar_location' => 'bottom',
    'theme_advanced_resizing' => 'true'
    )
  )
);
```

I also just noticed, when I `pr($this->TinyMCE);`

I get:

```
TinyMCE\View\Helper\TinyMCEHelper Object
(
    [helpers] => Array
        (
            [0] => Html
        )

    [theme] => 
    [plugin] => 
    [fieldset] => Array
        (
        )

    [tags] => Array
        (
        )

    [implementedEvents] => Array
        (
            [View.beforeRender] => beforeRender
        )

    [_config] => Array
        (
        )

)
```

For some reason there is nothing in [theme] value, it should be - advanced. What am I doing wrong? Is something wrong with this line - `$this->TinyMCE->editor(array('theme' => 'advanced'));` ?

**Comment by hgnelson83** [comment]
What Cake version are you using? I don't think I can help you here, is just that I can't make this plugin to work with cake 3.x. I was wondering if it is compatible with Cake 3.3.x

**Comment by andrej-griniuk** [comment]
@clevertechie you don't need to surround it with `<textarea>`, just `$this->TinyMCE->editor(array('theme' => 'advanced'));`

**Comment by andrej-griniuk** [comment]
@hgnelson83 there is 3.x branch for CakePHP 3.x version

**Comment by feldmarv** [comment]
What was the problem here? I have the same issue
