### ISSUE TITLE
What am I doing wrong? Error: TinyMCE.TinyMCEHelper could not be found

### ISSUE THREAD

**Issue by hgnelson83** [CakeDC/TinyMCE#48]
These are the steps that I am following after reading the docs. I am using Cake 3.3.x.

(1) Downloaded the master file of TinyMCE as a zip file. 
(2) Extracted it to plugins/TinyMCE folder in my app. Now it has the following directory structure: 
- plugins/TinyMCE/Docs
- plugins/TinyMCE/Test
- plugins/TinyMCE/View
- plugins/TinyMCE/webroot

(2) Replaced it with the 3.x branch. in the same directory
(3) Typed: `$this->Html->script('/TinyMCE/js/tiny_mce4/tinymce.min.js', ['block' => true]); ` in the layout but doesnt load any javascript or display any error after or before I loaded jquery version 1.11.3.
(4) Since the above didn't work, I erased it and loaded the helper in the specific Controller where I wanted to use it (not the general AppController). Right after calling the class of the controller  I wrote: `public $helpers = ['TinyMCE.TinyMCE'];`
(5) Tried loading in the view top the following: `$this->TinyMCE->editor(['theme' => 'modern', 'selector' => 'textarea']);` gives the above error: 

```
Error: TinyMCE.TinyMCEHelper could not be found.
Make sure your plugin TinyMCE is in the D:\wamp\www\testingapp\plugins\ directory and was loaded.

Error: Create the class TinyMCEHelper below in file: D:\wamp\www\testingapp\plugins\TinyMCE\src\View\Helper\TinyMCEHelper.php

<?php
namespace TinyMCE\View\Helper;
use Cake\View\Helper;
class TinyMCEHelper extends Helper
{

}
```
I followed the path shown in the error above, and the file TinyMCEHelper.php does exists with all the code inside. I am under wamp 3.0.4. with short tags off.

What am I missing here? Please help me.

**Comment by feldmarv** [comment]
maybe load the plugin in config/bootstrap.php

Plugin::load('TinyMCE', ['autoload' => true]);

**Comment by hgnelson83** [comment]
Loading the plugin from the bootstrap removed the error above, but the Editor wasnt showing up or replacing the default textarea. The problem was that I removed `<?= $this->fetch('script') ?>` from the layout. The moment I put that line back in the layout it worked.
Case closed !! Thanks.

**Comment by Megslalk** [comment]
Hi! Closing issue - please re-open if you experience anything similar
